# Generated by Django 5.0.7 on 2024-07-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
